#!/bin/bash

# example launch script

## Files and cmd
FILE="$HOME/.cache/eww_launch.lock"
EWW="/usr/local/bin/eww -c $HOME/.config/eww"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} open-many \
         top_bar
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} close-all && killall eww
	rm "$FILE"
fi
