service_bind_address    192.168.10.1
dns_default_ip          192.168.10.1

start_service dns
start_service http
start_service https
start_service smtp
start_service smtps
start_service pop3
start_service pop3s
start_service ftp
start_service ftps
start_service tftp
start_service irc
start_service ntp
start_service finger
start_service ident
start_service syslog
start_service time_tcp
start_service time_udp
start_service daytime_tcp
start_service daytime_udp
start_service echo_tcp
start_service echo_udp
start_service discard_tcp
start_service discard_udp
start_service quotd_tcp
start_service quotd_udp
start_service chargen_tcp
start_service chargen_udp
start_service dummy_tcp
start_service dummy_udp

dns_default_hostname    www

http_fakefile		    txt	    sample.txt	    text/plain
http_fakefile		    htm	    sample.html	    text/html
http_fakefile		    html	sample.html	    text/html
http_fakefile		    php	    sample.html	    text/html
http_fakefile		    gif	    sample.gif	    image/gif
http_fakefile		    jpg	    sample.jpg	    image/jpeg
http_fakefile		    jpeg	sample.jpg	    image/jpeg
http_fakefile		    png	    sample.png	    image/png
http_fakefile		    bmp	    sample.bmp	    image/x-ms-bmp
http_fakefile		    ico	    favicon.ico	    image/x-icon
http_fakefile		    exe	    sample_gui.exe	x-msdos-program
http_fakefile		    com	    sample_gui.exe	x-msdos-program

https_fakefile		    txt	    sample.txt	    text/plain
https_fakefile		    htm	    sample.html	    text/html
https_fakefile		    html	sample.html	    text/html
https_fakefile		    php	    sample.html	    text/html
https_fakefile		    gif	    sample.gif	    image/gif
https_fakefile		    jpg	    sample.jpg	    image/jpeg
https_fakefile		    jpeg	sample.jpg	    image/jpeg
https_fakefile		    png	    sample.png	    image/png
https_fakefile		    bmp	    sample.bmp	    image/x-ms-bmp
https_fakefile		    ico	    favicon.ico	    image/x-icon
https_fakefile		    exe	    sample_gui.exe	x-msdos-program
https_fakefile		    com	    sample_gui.exe	x-msdos-program

http_default_fakefile   sample.html	text/html
https_default_fakefile  sample.html	text/html

##########################################################################
#
# Fake files returned in fake mode based on static path (this can also be
# done with the same syntax for HTTPS).
# The fake files must be placed in <data-dir>/http/fakefiles
#
# Syntax: http(s)_static_fakefile <request_path> <filename> <mime_type>
#
# http_static_fakefile	/path/			  sample_gui.exe x-msdos-program
# http_static_fakefile	/path/to/file.exe sample_gui.exe x-msdos-program
# https_static_fakefile	/path/			  sample_gui.exe x-msdos-program
# https_static_fakefile	/path/to/file.exe sample_gui.exe x-msdos-program
# 
##########################################################################
