# from `https://github.com/alacritty/alacritty-theme`
import = [ "~/.config/alacritty/themes/themes/tokyo-night.toml" ]
live_config_reload = true

[scrolling]
history = 10000
multiplier = 3

[font]
size = 10.0

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFont"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Regular"

[shell]
args = ["--login", "-c", "tmux"]
program = "/usr/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 1.0

[window.class]
general = "Alacritty"

[window.padding]
x = 25
y = 25
