
[scrolling]
history = 50000
multiplier = 3

[font]
size = 10.5

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFont"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Regular"

[terminal.shell]
args = ["--login", "-c", "tmux"]
program = "/usr/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0

[window.class]
general = "Alacritty"

[window.padding]
x = 10
y = 9

[general]
live_config_reload = true
# from `https://github.com/alacritty/alacritty-theme`
import = [ "~/.config/alacritty/themes/themes/tokyo-night.toml" ]

[terminal]
