#!/bin/bash

get_music_title() {
    # if [ "$(playerctl status)" == "Playing" ]; then
        echo $(playerctl -p spotify_player metadata --format '{{title}}')
    #else
    #    echo "offline"
    #fi
}

get_music_artist() {
    #if [ "$(playerctl status)" == "Playing" ]; then
    echo $(playerctl -p spotify_player metadata --format '- {{artist}}')
    #else
    #    echo "unknown"
    #fi
}

get_music_status() {
    status=$(playerctl -p spotify_player status --no-messages)

    if [ "$status" == "Playing" ]; then
        echo " "
    else
        echo " "
    fi
}


case "$1" in
    "-t"       ) get_music_title ;;
    "-a"      ) get_music_artist ;;
    "-s"      ) get_music_status ;;
esac
