#!/usr/bin/env bash

# DOESNT WORK YET LMAO

CURRENT_VIEWPORT='2560,0'
WINDOWS=$(wmctrl -l)
WNAME1_LOCK="$HOME/.cache/eww_active_window1.lock"
[ ! -f "$WNAME1_LOCK" ] && touch "$WNAME1_LOCK"

while read -r line; do

  WINDOW_ID=$(echo "$line" | awk '{print $1}')
  WINDOW_WORKSPACE=$(echo "$line" | awk '{print $2}')
  WINDOW_VIEWPORT=$(wmctrl -d | grep "^$WINDOW_WORKSPACE" | awk '{print $6}')

  if [ "$WINDOW_VIEWPORT" == "$CURRENT_VIEWPORT" ]; then

    ACTIVE_WINDOW_HEX=$(xprop -root _NET_ACTIVE_WINDOW | awk '{print $5}')
    ACTIVE_WINDOW_ID=$(printf "0x%08x" "$ACTIVE_WINDOW_HEX")

    if [ "$WINDOW_ID" == "$ACTIVE_WINDOW_ID" ]; then
      WIN_NAME=$(xprop -id "$ACTIVE_WINDOW_HEX" WM_NAME | sed -n 's/.*= "\(.*\)"/\1/p')
      echo "$ACTIVE_WINDOW_HEX" > "$WNAME1_LOCK"
      echo "$WIN_NAME"

    else
        INACT_WIN_NAME=$(cat "$WNAME1_LOCK")
        WIN_NAME=$(xprop -id "$INACT_WIN_NAME" WM_NAME | sed -n 's/.*= "\(.*\)"/\1/p')
        echo "$WIN_NAME"
        break

    fi


  fi



done <<< "$WINDOWS"
