#!/bin/bash

# Get the ID of the currently active window
ACTIVE_WIN_ID=$(xprop -root _NET_ACTIVE_WINDOW | awk '{print $5}' | sed 's/,//' | sed 's/^0x/0x0/')

# Get the name of the active window using its ID
if [ "$ACTIVE_WIN_ID" = "0x0" ]; then
    echo "No active window"
else
    ACTIVE_WIN_NAME=$(xprop -id "$ACTIVE_WIN_ID" WM_NAME | sed -n 's/.*= "\(.*\)"/\1/p')
    echo "$ACTIVE_WIN_NAME"
fi
