#!/bin/bash

# total utilization
get_total_cpu_usage() {
    mpstat | awk '/all/ {print 100 - $NF}'
}

# core utilization
get_core_usage() {
    echo $(mpstat -P ALL 1 1 | awk '/Average:/ && $2 ~ /[0-9]+/ {
        core_utilization[int($2/4)] = core_utilization[int($2/4)] "Core " $2 ": " 100 - $NF"% | "
    }
    END {
        for (i in core_utilization) {
            print core_utilization[i]
        }
    }')
}

# CPU temp
get_cpu_temp() {
    echo $(sensors | awk '/^Package id 0:/ {gsub("\\+","",$4); print $4}')
}

get_icon() {
    echo "";
}

# handle args
case "$1" in
    total) 
        get_total_cpu_usage 
        ;;
    temp) 
        get_cpu_temp 
        ;;
    icon)
        get_icon
        ;;
    *) 
        echo "Usage: $0 {total|cores|temp}" 
        ;;
esac
