#!/bin/bash

get_volume() {
	status=`amixer get Master | tail -n1 | grep -wo 'on'`

	if [[ "$status" == "on" ]]; then
		VOLUME=`amixer get Master | tail -n1 | awk -F ' ' '{print $5}' | tr -d '[%]'`;
		printf "%.0f\n" $VOLUME
	else
		echo "off"
	fi
}


# Get icons
get_icon() {
	vol="$(get_volume)"
	if [[ "$vol" == "mute" ]]; then
		echo "󰖁"
	elif (( vol == 0 )); then
		echo "󰖁"
	else
		echo "󰕾"
	fi
}

# Increase Volume
inc_volume() {
	amixer -Mq set Master,0 5%+ unmute
}

# Decrease Volume
dec_volume() {
	amixer -Mq set Master,0 5%- unmute
}

# Toggle Mute
toggle_mute() {
	status=`amixer get Master | tail -n1 | grep -wo 'on'`

	if [[ "$status" == "on" ]]; then
		amixer set Master toggle
	else
		amixer set Master toggle
	fi
}

# Execute accordingly
case "$1" in
	--get)
		get_volume
		;;
	--icon)
		get_icon
		;;
	--inc)
		inc_volume
		;;
	--dec)
		dec_volume
		;;
	--toggle)
		toggle_mute
		;;
	*)
		get_volume
		;;
esac